### PR TITLE
copyAtRoot keyword - a special path modifier

### PR DESCRIPTION
**Pull request by heyigor**
### copyAtRoot

This keyword is a variant of copy that will append a path onto the asset location. Thus creating a easy way to copy assets and preserve a folder location, like audio, svg, etc.
```
"copyAtRoot": [
  "sounds/sfx/add.wav#audio",
  "sounds/sfx/bad_pick_sound.wav#audio",
  "sounds/sfx/buildingsound.wav#audio",
  "sounds/sfx/click.wav#audio",
]
```

Hi guys!

### CODE REVIEW

**Comment by marnberg** [comment]
Hi Steve, 
Great addition and I think something we have discussed before. One option would be to convert to object array. One benefit to this is that it is self documenting. It would also potentially support urls where # is a keyword. Thoughts? 

"copyAtRoot": [
  { "file": "sounds/sfx/add.wav", "target":" audio"  },
  { "file": "video/demo.wav", "target":"video/demo"  },
  { "file":"images/icon.png" },
  { "url":"images/logo.png", "target":"logo/demo"  }
]

Cheers,
Martin

**Comment by heyigor** [comment]
@marnberg interesting idea! I'll ponder some more.

**Comment by heyigor** [comment]
@marnberg what do you think of:

```
"copyAtRoot": [
	{ "src": "sounds/sfx/add.wav", "dst":" audio" },
	{ "src": "video/demo.wav", "dst":"video/demo" },
	{ "src":"images/icon.png" },
	{ "src":"images/logo.png", "dst":"logo/demo" }
]
```

the distinction between file and url can be the http:// etc,

**Comment by marnberg** [comment]
Yes, that is fine with me. I'm generally more verbose not using abbreviations  but I don't think there would be any confusion over these.

"copyAtRoot": [
	{ "src": "sounds/sfx/add.wav", "dst":" audio" },
	{ "src": "video/demo.wav", "dst":"video/demo" },
	{ "src": "images/icon.png" },
	{ "src": "images/logo.png", "dst":"logo/demo" }
]
I was also thinking this actually does not conflict with the existing implementation. Lets say that you are only interested in root copy, you can just specify an array as you do today.
"copyAtRoot": [
	"sounds/sfx/add.wav",
	"video/demo.wav",
	"images/icon.png",
	"images/logo.png",
]

This way the destination implementation is just an extension.

**Pull request closed without merging**
